### ISSUE TITLE
Automate Marain deployment

### ISSUE THREAD

**Issue by idg10** [marain-dotnet/Marain.Instance#1]
The primary purpose of this repo is to make it possible to deploy entire Marain environments. The following things need to happen:

- [x] get complete initial basic implementation of common deployment scripts in place #2
- [x] Parameterize build pipeline #6  
- [x] Deploy Marain.Tenancy successfully (because everything needs this) https://github.com/marain-dotnet/Marain.Tenancy/issues/48
- [x] Enable cross-service auth setup https://github.com/marain-dotnet/Marain.Instance/issues/9
- [x] Deploy Marain.Operations (because until we deploy at least one thing besides Tenancy, we can't reasonably claim we're done) https://github.com/marain-dotnet/Marain.Operations/issues/66
